export const availableComponents = [
  {
    type: 'action',
    label: 'Action',
    icon: 'heroicons:bolt',
    component: 'div',
    props: {
      onNew: '',
      onGet: '',
      onRead: '',
      onGetDetail: [],
      onCreate: '',
      onCreateDetail: [],
      onUpdate: '',
      onUpdateDetail: [],
      onUpload: '',
      onPurge: '',
      onPurgeDetail:[],
      onPdf: '',
      onXls: '',
      onLockFlow: '',
      onCopy: '',
    },
  },
  {
    type: 'bool',
    label: 'Boolean',
    icon: 'heroicons:check-circle',
    component: 'input',
    props: {
      key: '',
      label: '',
      place: '',
      text: '',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'button',
    label: 'Button',
    icon: 'heroicons:stop',
    component: 'UButton',
    props: {
      text: 'Button',
      class: 'px-4 py-2 rounded transition',
      icon: 'heroicons:plus',
      onClick: '',
    },
  },
  {
    type: 'callother',
    label: 'Call Other',
    icon: 'heroicons:arrow-path',
    component: 'div',
    props: {
      key: '',
      othertype: '',
      otherkey: '',
      class: '',
    },
  },
  {
    type: 'color',
    label: 'Color',
    icon: 'heroicons:swatch',
    component: 'input',
    props: {
      key: '',
      text: 'Color',
      place: 'Enter a color',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'date',
    label: 'Date',
    icon: 'heroicons:calendar',
    component: 'input',
    props: {
      key: '',
      text: 'Date',
      place: 'Enter a date',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'datetime',
    label: 'Date Time',
    icon: 'heroicons:calendar-days',
    component: 'input',
    props: {
      key: '',
      text: 'Date Time',
      place: 'Enter a date time',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'email',
    label: 'Email',
    icon: 'heroicons:envelope',
    component: 'input',
    props: {
      key: '',
      label: 'Email',
      place: 'example@mail.com',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'file',
    label: 'File',
    icon: 'heroicons:document',
    component: 'input',
    props: {
      key: '',
      text: 'File',
      place: 'Enter a file',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'hidden',
    label: 'Hidden',
    icon: 'heroicons:eye-slash',
    component: 'input',
    props: {
      text: 'Hidden Text',
      place: 'Enter a text',
      key: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'image',
    label: 'Image',
    icon: 'heroicons:photo',
    component: 'input',
    props: {
      key: '',
      text: 'Image',
      place: 'Enter a image',
      src: '',
      class: '',
      isinput: false,
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'label',
    label: 'Label',
    icon: 'heroicons:tag',
    component: 'label',
    props: {
      key: '',
      text: 'Label',
      place: 'Enter label',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'longtext',
    label: 'Long Text',
    icon: 'heroicons:document-text',
    component: 'textarea',
    props: {
      key: '',
      label: 'Long Text',
      place: 'Enter long text',
      text: 'Long Text',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'month',
    label: 'Month',
    icon: 'heroicons:calendar',
    component: 'input',
    props: {
      key: '',
      text: 'Month',
      place: 'Enter a month',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'number',
    label: 'Number',
    icon: 'heroicons:calculator',
    component: 'input',
    props: {
      key: '',
      label: 'Number',
      place: 'enter a number',
      text: '',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'password',
    label: 'Password',
    icon: 'heroicons:lock-closed',
    component: 'input',
    props: {
      key: '',
      place: 'enter a password',
      text: '',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'radio',
    label: 'Radio',
    icon: 'heroicons:radio',
    component: 'input',
    props: {
      key: '',
      text: 'Radio',
      place: 'Enter a radio',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'range',
    label: 'Range',
    icon: 'heroicons:adjustments-horizontal',
    component: 'input',
    props: {
      key: '',
      text: 'Range',
      place: 'Enter a range',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'reset',
    label: 'Reset',
    icon: 'heroicons:arrow-path',
    component: 'input',
    props: {
      key: '',
      text: 'Reset',
      place: 'Enter a reset',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'select',
    label: 'Select',
    icon: 'heroicons:list-bullet',
    component: 'input',
    props: {
      key: '',
      text: '',
      source: '',
      label: '',
      place: 'Choose a data',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'selectgroup',
    label: 'Select Group',
    icon: 'heroicons:queue-list',
    component: 'div',
    props: {
      key: '',
      text: '',
      source: '',
      sourceAll: '',
      label: '',
      place: 'Choose a data',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'tel',
    label: 'Tel',
    icon: 'heroicons:phone',
    component: 'input',
    props: {
      key: '',
      text: 'Tel',
      place: 'Enter a tel',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'text',
    label: 'Text',
    icon: 'heroicons:pencil-square',
    component: 'input',
    props: {
      key: '',
      text: 'Text',
      place: 'Enter a text',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'time',
    label: 'Time',
    icon: 'heroicons:clock',
    component: 'input',
    props: {
      key: '',
      text: 'Time',
      place: 'Enter a time',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'url',
    label: 'Url',
    icon: 'heroicons:link',
    component: 'input',
    props: {
      key: '',
      text: 'Url',
      place: 'Enter a url',
      class: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'title',
    label: 'Title',
    icon: 'mdi:format-header-1',
    component: 'div',
    props: {
      text: 'title',
      class: 'tracking-tight mb-4',
    },
  },
  {
    type: 'subtitle',
    label: 'Sub Title',
    icon: 'mdi:format-header-2',
    component: 'div',
    props: {
      text: 'Sub Title',
      class: 'tracking-tight mb-4',
    },
  },
];

export const layoutContainers = [
  {
    type: 'buttons',
    label: 'Buttons',
    icon: 'heroicons:stop',
    component: 'div',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'chart',
    label: 'Chart',
    icon: 'heroicons:chart-bar',
    component: 'div',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
      charttype: '',
      searchflow: '',
      title: '',
      description: '',
      xaxis: '',
      yaxis: '',
    },
    children: [],
  },
  {
    type: 'charts',
    label: 'Charts',
    icon: 'heroicons:chart-pie',
    component: 'div',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'card',
    label: 'Card',
    icon: 'heroicons:credit-card',
    component: 'div',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
      spotlight: false,
      spotlightcolor: 'primary',
      title: '',
      description: '',
      icon: '',
      orientation: 'vertical',
      searchflow: '',
    },
  },
  {
    type: 'cards',
    label: 'Cards',
    icon: 'heroicons:squares-2x2',
    component: 'div',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'columns',
    label: 'Columns',
    icon: 'heroicons:view-columns',
    component: 'div',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'form',
    label: 'Form',
    icon: 'heroicons:clipboard-document-list',
    component: 'div',
    props: {
      class: 'w-full',
      key: 'form',
      primary: '',
    },
    children: [],
  },
  {
    type: 'master',
    label: 'Master',
    icon: 'heroicons:document-duplicate',
    component: 'div',
    props: {
      class: 'w-full',
      layout: 'standard',
      key: 'master',
      primary: '',
      lock: false,
    },
    children: [],
  },
  {
    type: 'modals',
    label: 'Modals',
    icon: 'heroicons:window',
    component: 'div',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'modal',
    label: 'Modal',
    icon: 'heroicons:window',
    component: 'div',
    props: {
      key: '',
      text: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'search',
    label: 'Search',
    icon: 'heroicons:magnifying-glass',
    component: 'div',
    props: {
      key: '',
      class: '',
    },
    children: [],
  },
  {
    type: 'tabs',
    label: 'Tabs',
    icon: 'heroicons:folder',
    component: 'UTab',
    props: {
      key: 'tabs',
      class: 'w-full mb-4',
    },
    children: [],
  },
  {
    type: 'tab',
    label: 'Tab',
    icon: 'heroicons:folder-open',
    component: 'div',
    props: {
      key: 'tab',
      class: 'w-full mb-4',
      text: '',
    },
    children: [],
  },
  {
    type: 'table',
    label: 'Table',
    icon: 'heroicons:table-cells',
    component: 'div',
    props: {
      key: 'table0',
      isdetail: false,
      primary: '',
      relationkey: '',
      text: '',
      source: '',
      class: 'w-full mb-4',
      isselectall: true,
      enablecheck: true,
      isexpand: false,
    },
    children: [],
  },
  {
    type: 'detailtable',
    label: 'Detail Table (Inline)',
    icon: 'heroicons:table-cells',
    component: 'div',
    props: {
      key: 'table0',
      isdetail: false,
      primary: '',
      relationkey: '',
      text: '',
      source: '',
      class: 'w-full mb-4',
      isselectall: true,
      enablecheck: true,
      isexpand: false,
    },
    children: [],
  },
  {
    type: 'tables',
    label: 'Tables',
    icon: 'heroicons:table-cells',
    component: 'div',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'widget',
    label: 'Widget',
    icon: 'heroicons:puzzle-piece',
    component: 'div',
    props: {
      class: 'w-full',
      layout: 'standard',
      key: 'widget',
      primary: '',
    },
    children: [],
  },
  {
    type: 'wizard',
    label: 'Wizard',
    icon: 'heroicons:play-circle',
    component: 'div',
    props: {
      class: 'w-full',
      layout: 'standard',
      key: 'wizard',
      primary: '',
    },
    children: [],
  },
  {
    type: 'row',
    label: 'Row / Section',
    icon: 'heroicons:bars-3',
    component: 'div',
    props: {
        key: 'row_1',
        class: 'flex flex-row flex-wrap w-full gap-2',
    },
    children: [],
  },
  {
    type: 'col',
    label: 'Column',
    icon: 'heroicons:view-columns',
    component: 'div',
    props: {
        key: 'col_1',
        class: 'flex flex-col w-full md:w-1/2 p-2',
    },
    children: [],
  },
  {
    type: 'step',
    label: 'Step',
    icon: 'heroicons:forward',
    component: 'div',
    props: {
      key: 'step_1',
      title: 'Step Title',
      class: 'w-full',
    },
    children: [],
  },
  {
    type: 'kanban',
    label: 'Kanban Board',
    icon: 'heroicons:view-columns',
    component: 'div',
    props: {
      key: 'kanban_1',
      class: 'w-full',
      source: '',
      primary: '',
      titlefield: 'title',
      descriptionfield: 'description',
      statusfield: 'status',
      assigneefield: 'assignee',
      duedatefield: 'duedate',
      priorityfield: 'priority',
      tagsfield: 'tags',
      onUpdate: '',
      onUpdateStatus: '',
    },
    children: [],
  },
  {
    type: 'kanbanboard',
    label: 'Kanban Board',
    icon: 'heroicons:view-columns',
    component: 'KanbanBoard',
    props: {
      key: 'kanban_1',
      // Data source workflows
      projectsSource: '', // workflow to fetch projects
      cardsSource: '', // workflow to fetch cards
      // Project CRUD workflows
      onCreateProject: '', // workflow to create project
      onUpdateProject: '', // workflow to update project
      onDeleteProject: '', // workflow to delete project
      // Card CRUD workflows
      onCreateCard: '', // workflow to create card
      onUpdateCard: '', // workflow to update card
      onDeleteCard: '', // workflow to delete card
      onMoveCard: '', // workflow to move card between columns
      // Attachment workflows
      onUploadAttachment: '', // workflow to upload attachment
      onDeleteAttachment: '', // workflow to delete attachment
      // Column configuration (customizable)
      columns: [
        { status: 'backlog', title: 'Backlog', icon: '📋', color: '#6b7280' },
        { status: 'todo', title: 'To Do', icon: '📝', color: '#3b82f6' },
        { status: 'inprogress', title: 'In Progress', icon: '⚡', color: '#f59e0b' },
        { status: 'review', title: 'Review', icon: '👀', color: '#8b5cf6' },
        { status: 'done', title: 'Done', icon: '✅', color: '#10b981' },
      ],
      // Features
      enableAttachments: true, // enable file attachments
      enableClipboardPaste: true, // enable Ctrl+V image paste
      enableColumnManagement: true, // enable column reordering and customization
      enableDragDrop: true, // enable drag and drop
      class: '',
    },
    children: [],
  },
  {
    type: 'kanbancolumn',
    label: 'Kanban Column',
    icon: 'heroicons:rectangle-stack',
    component: 'div',
    props: {
      key: 'column_1',
      title: 'To Do',
      status: 'todo',
      color: 'gray',
      limit: 0,
      class: '',
    },
    children: [],
  },
  {
    type: 'kanbancard',
    label: 'Kanban Card',
    icon: 'heroicons:credit-card',
    component: 'div',
    props: {
      key: 'card_1',
      class: '',
    },
    children: [],
  },
  {
    type: 'orgchart',
    label: 'Org Chart',
    icon: 'heroicons:user-group',
    component: 'FormOrgChart',
    props: {
      key: 'orgchart_1',
      source: '', // Dataflow to fetch nodes
      onCreate: '', // Flow to create node
      onUpdate: '', // Flow to update node (move/reparent)
      onDelete: '', // Flow to delete node
      modalKey: '', // Modal to open for editing/creating
      config: {
        nodeKey: 'id',
        parentKey: 'parent_id',
        labelKey: 'name',
        titleKey: 'title',
        imageKey: 'avatar'
      },
      class: 'w-full h-[600px]',
    },
    children: [],
  }
];
