export const availableComponents = [
  {
    type: 'bool',
    label: 'Boolean',
    props: {
      key: '',
      label: '',
      place: '',
      text: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'button',
    label: 'Button',
    props: {
      text: 'Button',
      class: 'px-4 py-2 rounded transition',
      icon: 'heroicons:plus',
      onClick: '',
    },
  },
  {
    type: 'color',
    label: 'Color',
    props: {
      key: '',
      text: 'Color',
      place: 'Enter a color',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'date',
    label: 'Date',
    props: {
      key: '',
      text: 'Date',
      place: 'Enter a date',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'datetime',
    label: 'Date Time',
    props: {
      key: '',
      text: 'Date Time',
      place: 'Enter a date time',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'email',
    label: 'Email',
    props: {
      key: '',
      label: 'Email',
      place: 'example@mail.com',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'file',
    label: 'File',
    props: {
      key: '',
      text: 'File',
      place: 'Enter a file',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'hidden',
    label: 'Hidden',
    props: {
      text: 'Hidden Text',
      place: 'Enter a text',
      key: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'image',
    label: 'Image',
    props: {
      key: '',
      text: 'Image',
      place: 'Enter a image',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'longtext',
    label: 'Long Text',
    props: {
      key: '',
      label: 'Long Text',
      place: 'Enter long text',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'month',
    label: 'Month',
    props: {
      key: '',
      text: 'Month',
      place: 'Enter a month',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'number',
    label: 'Number',
    props: {
      key: '',
      label: 'Number',
      place: 'enter a number',
      text: '',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'radio',
    label: 'Radio',
    props: {
      key: '',
      text: 'Radio',
      place: 'Enter a radio',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'range',
    label: 'Range',
    props: {
      key: '',
      text: 'Range',
      place: 'Enter a range',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'reset',
    label: 'Reset',
    props: {
      key: '',
      text: 'Reset',
      place: 'Enter a reset',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'select',
    label: 'Select',
    props: {
      key: '',
      text: '',
      source: '',
      label: '',
      place: 'Choose a data',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'tel',
    label: 'Tel',
    props: {
      key: '',
      text: 'Tel',
      place: 'Enter a tel',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'text',
    label: 'Text',
    props: {
      key: '',
      text: 'Text',
      place: 'Enter a text',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'time',
    label: 'Time',
    props: {
      key: '',
      text: 'Time',
      place: 'Enter a time',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'url',
    label: 'Url',
    props: {
      key: '',
      text: 'Url',
      place: 'Enter a url',
      primary: false,
      enabled: true,
      required: false,
    },
  },
  {
    type: 'title',
    label: 'Title',
    props: {
      text: 'title',
      class: 'tracking-tight mb-4',
    },
  },
  {
    type: 'subtitle',
    label: 'Sub Title',
    props: {
      text: 'Sub Title',
      class: 'tracking-tight mb-4',
    },
  },
  {
    type: 'action',
    label: 'Action',
    props: {
      onNew: '',
      onGet: '',
      onRead: '',
      onGetDetail: [],
      onCreate: '',
      onUpdate: '',
      onUpload: '',
      onPurge: '',
      onPdf: '',
      onXls: '',
    },
  },
];

export const layoutContainers = [
  {
    type: 'master',
    label: 'Master',
    props: {
      class: 'w-full',
      layout: 'standard',
      key: 'master',
      primary: '',
    },
    children: [],
  },
  {
    type: 'widget',
    label: 'Widget',
    props: {
      class: 'w-full',
      layout: 'standard',
      key: 'widget',
      primary: '',
    },
    children: [],
  },
  {
    type: 'form',
    label: 'Form',
    props: {
      class: 'w-full',
      key: 'form',
      primary: '',
    },
    children: [],
  },
  {
    type: 'buttons',
    label: 'Buttons',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'table',
    label: 'Table',
    props: {
      key: 'table0',
      primary: '',
      relationkey: '',
      text: '',
      source: '',
      class: 'w-full mb-4',
    },
    children: [],
  },
  {
    type: 'tables',
    label: 'Tables',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'search',
    label: 'Search',
    props: {
      key: '',
      class: '',
    },
    children: [],
  },
  {
    type: 'columns',
    label: 'Columns',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'modals',
    label: 'Modals',
    props: {
      key: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
  {
    type: 'modal',
    label: 'Modal',
    props: {
      key: '',
      text: '',
      class: 'flex flex-wrap gap-2 mb-3',
    },
    children: [],
  },
];
